# Generated by Django 2.1.4 on 2018-12-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181213_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_pic',
            field=models.ImageField(default='Blog/img/blog.jpg', upload_to='Blog/img'),
        ),
    ]
