# Generated by Django 2.1.4 on 2018-12-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181217_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AddField(
            model_name='post',
            name='post_pic_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
