# Generated by Django 2.1.4 on 2018-12-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20181222_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('PE', 'Opiniones y Temas Personales'), ('DA', 'Tratamiento de Datos'), ('DE', 'Django y Python'), ('RE', 'Recetas de La Terreta'), ('MI', 'Articulos Relacionaos con mi Sitio web')], default='PE', max_length=2),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_pic_url',
            field=models.CharField(max_length=200),
        ),
    ]
